# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1497890078);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1497890198);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1497889718);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1497889958);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1497889838);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1497890318);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1478644590);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.migration.version", 38);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1497891406309");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1497893170309");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1497889617102");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1497893217102");
user_pref("browser.search.countryCode", "GB");
user_pref("browser.search.region", "GB");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20161021084537");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20161021084537");
user_pref("browser.startup.homepage_override.mstone", "49.0.2");
user_pref("browser.startup.page", 3);
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 2);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20170619);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1478644656856");
user_pref("datareporting.sessions.current.activeTicks", 110);
user_pref("datareporting.sessions.current.firstPaint", 12199);
user_pref("datareporting.sessions.current.main", 1952);
user_pref("datareporting.sessions.current.sessionRestored", 12496);
user_pref("datareporting.sessions.current.startTime", "1497889591018");
user_pref("datareporting.sessions.current.totalTime", 3363);
user_pref("datareporting.sessions.currentIndex", 4);
user_pref("datareporting.sessions.prunedIndex", 3);
user_pref("dom.apps.lastUpdate.buildID", "20161021084537");
user_pref("dom.apps.lastUpdate.mstone", "49.0.2");
user_pref("dom.apps.reset-permissions", true);
user_pref("e10s.rollout.cohort", "test");
user_pref("e10s.rollout.cohortSample", "0.826267");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"asyncrendering@mozilla.org\":{\"version\":\"2.0\",\"type\":\"extension\",\"descriptor\":\"/home/james/.mozilla/firefox/acg91dha.default/features/{d8fcaddc-fba6-491f-9602-a39ac63af49a}/asyncrendering@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"e10srollout@mozilla.org\":{\"version\":\"1.3\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"firefox@getpocket.com\":{\"version\":\"1.0.4\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "49a");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:49.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1497890079);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20170302.01");
user_pref("extensions.lastAppVersion", "49.0.2");
user_pref("extensions.lastPlatformVersion", "49.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{f8d9b46a-3824-4a0d-992a-0992ece89da1}\",\"addons\":{\"asyncrendering@mozilla.org\":{\"version\":\"2.0\"},\"websensehelper@mozilla.org\":{\"version\":\"2.0\"}}}");
user_pref("extensions.xpiState", "{\"app-system-addons\":{\"asyncrendering@mozilla.org\":{\"d\":\"/home/james/.mozilla/firefox/acg91dha.default/features/{d8fcaddc-fba6-491f-9602-a39ac63af49a}/asyncrendering@mozilla.org.xpi\",\"e\":true,\"v\":\"2.0\",\"st\":1478645071000}},\"app-system-defaults\":{\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.3\",\"st\":1477041955000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.4\",\"st\":1477041955000},\"webcompat@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1477041955000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"49.0.2\",\"st\":1477041955000}}}");
user_pref("idle.lastDailyNotification", 1497889907);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1478644658);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20161021084537");
user_pref("media.gmp-manager.lastCheck", 1497889663);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1497889910);
user_pref("places.history.expiration.transient_current_max_pages", 97096);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1497889909);
user_pref("toolkit.startup.last_success", 1497889592);
user_pref("toolkit.telemetry.cachedClientID", "5fa03bc2-12e9-4835-b6af-d421fb702f61");
user_pref("toolkit.telemetry.previousBuildID", "20161021084537");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
