#!/bin/bash

sudo cp -rLf /etc/adduser.conf ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/locale.gen ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/locale.conf ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/localtime ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/vconsole.conf ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/crontab ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/crouton ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/dconf/ ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/debconf.conf ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/default/ ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/environment ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/fonts/ ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/fstab ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/host* ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/kbd/ ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/lsb-release ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/modprobe.d/ ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/networks ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/profile.d/ ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/profile ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/purple/prefs.xml ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/resolv.conf ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/resolvconf/ ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/sysctl.conf ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/sysctl.d/ ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/skel/ ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/xfce4 ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/xdg/ ~/.dotfiles/reference/etc/
sudo cp -rLf /etc/X11/ ~/.dotfiles/reference/etc/
